extends Node

class_name Recebe

@export var pergunta1:String
@export var pergunta2:String
@export var pergunta3:String
@export var pergunta4:String
@export var pergunta5:String
@export var pergunta6:String
@export var pergunta7:String
@export var pergunta8:String
@export var pergunta9:String
@export var pergunta10:String
@export var pergunta11:String
@export var pergunta12:String
@export var pergunta13:String
@export var pergunta14:String
@export var pergunta15:String
@export var pergunta16:String
@export var pergunta17:String
@export var pergunta18:String
@export var opções1:Array[String]
@export var opções2:Array[String]
@export var opções3:Array[String]
@export var opções4:Array[String]
@export var opções5:Array[String]
@export var opções6:Array[String]
@export var opções7:Array[String]
@export var opções8:Array[String]
@export var opções9:Array[String]
@export var opções10:Array[String]
@export var opções11:Array[String]
@export var opções12:Array[String]
@export var opções13:Array[String]
@export var opções14:Array[String]
@export var opções15:Array[String]
@export var opções16:Array[String]
@export var opções17:Array[String]
@export var opções18:Array[String]
@export var resposta1:String
@export var resposta2:String
@export var resposta3:String
@export var resposta4:String
@export var resposta5:String
@export var resposta6:String
@export var resposta7:String
@export var resposta8:String
@export var resposta9:String
@export var resposta10:String
@export var Resposta11:String
@export var Resposta12:String
@export var Resposta13:String
@export var Resposta14:String
@export var Resposta15:String
@export var Resposta16:String
@export var Resposta17:String
@export var Resposta18:String
